AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Elastic Beanstalk Service Catalog product. (fdp-1qj64b371)

Parameters:
  PortfolioProvider:
    Type: String
    Description: Owner and Distributor Name
  LaunchConstraintRole:
    Type: String
    Description: ARN of the launch constraint role for Beanstalk products.
  PortfolioId:
    Type: String
    Description: The ServiceCatalog portfolio this product will be attached to.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
  GlobalAllowlistBucketPrefix:
    Type: String
    Description: Bucket name prefix for ebextensions validator allowlist bucket
  GlobalAllowlistFolderName:
    Type: String
    Description: Folder name of the global ebextensions validator allowlist
Resources:
  scbeanstalkproduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: AWS Elastic Beanstalk application
      Description: This product creates an Elastic Beanstalk application.
      Owner: !Ref 'PortfolioProvider'
      Distributor: !Ref 'PortfolioProvider'
      SupportDescription: Operations Team
      SupportEmail: support@yourcompany.com
      AcceptLanguage: en
      SupportUrl: http://helpdesk.yourcompany.com
      ProvisioningArtifactParameters:
        # - Description: init
        #   Info:
        #     LoadTemplateFromURL: !Sub ${RepoRootURL}out-sc-elasticbeanstalk-ra-v1.yaml
        #   Name: v1
        # - Description: fix IMDSv1
        #   Info:
        #     LoadTemplateFromURL: !Sub ${RepoRootURL}out-sc-elasticbeanstalk-ra-v2.yaml
        #   Name: v2
        - Description: standard
          Info:
            LoadTemplateFromURL: !Sub ${RepoRootURL}out-sc-elasticbeanstalk-ra.yaml
          Name: v1.0

  EbextensionsValidatorBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${RepoRootURL}allowlist-bucket.yaml
      TimeoutInMinutes: 5
      Parameters:
        GlobalAllowlistFolderName: !Ref GlobalAllowlistFolderName
        GlobalAllowlistBucketPrefix: !Ref GlobalAllowlistBucketPrefix

  Associatebeanstalk:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'scbeanstalkproduct'
  constraintbeanstalk:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: Associatebeanstalk
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'scbeanstalkproduct'
      LocalRoleName: !Ref 'LaunchConstraintRole'
      Description: !Ref 'LaunchConstraintRole'
