image: python:3.8

stages:
  - test
  - artifact
  - package
  - deploy

test:
  stage: test
  before_script:
    - apt-get -y update && apt-get -y autoremove && apt-get clean && apt-get install -y jq
    - pip install pytest --upgrade
    - pip install -r ebextensions-validator/requirements.txt
    - pip install ./ebextensions-validator -t sc-elasticbeanstalk/application_deployment/ebextensions_validator
  script:
    - ROOT=$(pwd)
    - cd ebextensions-validator; pytest; cd $ROOT
    - cd sc-elasticbeanstalk/application_deployment; pytest; cd $ROOT

create-artifact-bucket:
  stage: artifact
  before_script:
    - apt-get -y update && apt-get -y autoremove && apt-get clean && apt-get install -y jq
    - pip install awscli aws-sam-cli --upgrade
    - ACCOUNT_ID=$(aws sts get-caller-identity | jq -r ".Account")
    - ARTIFACT_BUCKET_NAME=$ARTIFACT_BUCKET_NAME_PREFIX-$ACCOUNT_ID
  script:
    - if [[ `aws s3 ls | grep $ARTIFACT_BUCKET_NAME` == "" ]]; then aws s3 mb s3://$ARTIFACT_BUCKET_NAME; fi

package:
  stage: package
  before_script:
    - apt-get -y update && apt-get -y autoremove && apt-get clean && apt-get install -y jq
    - pip install awscli aws-sam-cli --upgrade
    - pip install ./ebextensions-validator -t sc-elasticbeanstalk/application_deployment/ebextensions_validator
    - ACCOUNT_ID=$(aws sts get-caller-identity | jq -r ".Account")
    - ARTIFACT_BUCKET_NAME=$ARTIFACT_BUCKET_NAME_PREFIX-$ACCOUNT_ID
  artifacts:
    untracked: true
  script:
    - ROOT=$(pwd)

    - cd sc-elasticbeanstalk
    - sh update_solution_stack_list.sh sc-elasticbeanstalk-ra.yaml > sc-elasticbeanstalk-ra_UPDATED.yaml
    - sam package --template-file sc-elasticbeanstalk-ra_UPDATED.yaml --output-template-file ../out-sc-elasticbeanstalk-ra.yaml --s3-bucket $ARTIFACT_BUCKET_NAME
    - cd $ROOT

    - cd allowlist-bucket
    - sam package --template-file allowlist-bucket.yaml --output-template-file ../out-allowlist-bucket.yaml --s3-bucket $ARTIFACT_BUCKET_NAME
    - cd $ROOT

    - aws s3 cp out-sc-elasticbeanstalk-ra.yaml s3://$ARTIFACT_BUCKET_NAME
    - aws s3 cp out-allowlist-bucket.yaml s3://$ARTIFACT_BUCKET_NAME/allowlist-bucket.yaml
    - aws cloudformation package --template-file sc-product-elasticbeanstalk.yaml --output-template-file out-sc-product-elasticbeanstalk.yaml --s3-bucket $ARTIFACT_BUCKET_NAME
    - aws s3 cp out-sc-product-elasticbeanstalk.yaml s3://$ARTIFACT_BUCKET_NAME/sc-product-elasticbeanstalk.yaml
    - aws s3 cp sc-portfolio-elasticbeanstalk.yaml s3://$ARTIFACT_BUCKET_NAME/sc-portfolio-elasticbeanstalk.yaml

deploy:
  stage: deploy
  dependencies:
    - package
  before_script:
    - apt-get -y update && apt-get -y autoremove && apt-get clean && apt-get install -y jq
    - pip install awscli --upgrade
    - ACCOUNT_ID=$(aws sts get-caller-identity | jq -r ".Account")
    - ARTIFACT_BUCKET_NAME=$ARTIFACT_BUCKET_NAME_PREFIX-$ACCOUNT_ID
  script:
    - aws cloudformation deploy --template-file sc-portfolio-elasticbeanstalk.yaml --stack-name $STACKNAME --parameter-overrides RepoRootURL=https://s3-eu-central-1.amazonaws.com/$ARTIFACT_BUCKET_NAME/ AllowRoleArn="arn:aws:iam::$ACCOUNT_ID:root" --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM
